# Detect Pi 5 models using PCI IDs
# Vendor: 14e4 (Broadcom), Device IDs: 2712 (Pi 5 Chip)
if lspci -nn | grep -q "14e4:2712"; then
  echo "Detected Raspberry Pi with 2712 chip. Installing support items..."

  sudo pacman -S --noconfirm --needed \
    linux-t2 \
    linux-t2-headers \
    apple-t2-audio-config \
    apple-bcm-firmware \
    t2fanrd \
    tiny-dfr

    linux-rpi-16k \
    linux-rpi-16k-headers \
    rpi5-eeprom \
    raspberrypi-bootloader \
    raspberrypi-utils \
    firmware-raspberrypi \
    arch-install-scripts \
    archlinuxarm-keyring

  echo "apple-bce" | sudo tee /etc/modules-load.d/t2.conf >/dev/null

  echo "MODULES+=(apple-bce usbhid hid_apple hid_generic xhci_pci xhci_hcd)" | sudo tee /etc/mkinitcpio.conf.d/apple-t2.conf >/dev/null

  cat <<EOF | sudo tee /etc/modprobe.d/brcmfmac.conf >/dev/null
# Fix for T2 MacBook WiFi connectivity issues
options brcmfmac feature_disable=0x82000
EOF

  sudo mkdir -p /etc/limine-entry-tool.d
  cat <<EOF | sudo tee /etc/limine-entry-tool.d/t2-mac.conf >/dev/null
# Generated by Omarchy installer for T2 Mac support
KERNEL_CMDLINE[default]+="intel_iommu=on iommu=pt pcie_ports=compat"
EOF
fi
